### ISSUE TITLE
Loading model error

### ISSUE THREAD

**Issue by wchuan163** [Digipom/WhisperCppAndroidDemo#1]
Couldn't create context with path /data/user/0/com.whispercppdemo/files/models/tiny.en.pt

8GB+128GB  android phone

**Comment by Digipom** [comment]
".pt" doesn't seem like the correct extension. It should be something like "ggml-tiny.bin". Please check this page: https://github.com/ggerganov/whisper.cpp/tree/master/models

**Comment by wchuan163** [comment]
"ggml-tiny.bin" it work, thanks

**Comment by Digipom** [comment]
Perfect :)
