### ISSUE TITLE
some fun not added !

### ISSUE THREAD

**Issue by michoael** [Digipom/WhisperCppAndroidDemo#4]
external fun initContextFromInputStream(inputStream: InputStream): Long
        external fun initContextFromAsset(assetManager: AssetManager, assetPath: String): Long
        external fun getSystemInfo(): String
        external fun benchMemcpy(nthread: Int): String
        external fun benchGgmlMulMat(nthread: Int): String

i can't try it but i build success i triad to add model on         external fun initContext(modelPath: String): Long
but i have error "Couldn't create context with path $filePath"

**Comment by Digipom** [comment]
For the context error, please ensure you copy the model to the assets folder. I'll go and sync with the latest Whisper code but you don't really need the bench stuff just to get transcriptions going. It will work even with the older code.

**Comment by michoael** [comment]
Yes,  thank you. Resolved error.

But when i try it transcripe simple say done, but don't print text. I don't know where issue
And when try with record, it's stay transcribing and don't finish

**Comment by Digipom** [comment]
Please run it in release mode. It will take a very long time in debug mode.

**Comment by michoael** [comment]
Thanks, it's working fine on release mode.
