### ISSUE TITLE
How change language and use translate? 

### ISSUE THREAD

**Issue by michoael** [Digipom/WhisperCppAndroidDemo#5]
I want change language to any another language from 98 languages supported and translate it do.

I tried to chang in parama translate true and change language to ar, but not work, still listening like English language and not translate

I downloaded ggml-model-whisper-tiny.bin so should be working with all languages, right?

What i should by work more?

**Comment by Digipom** [comment]
Hi, yes indeed it should. What does your params code look like? The translate is only supported for translating to English.

If you want to translate to other languages, there's an unsupported way to do it but it only works sometimes. You use the "transcribe" task and set the language to the one you want, and if you speak in other languages, sometimes it will get translated also.

However, the "translate" support is only for other languages --> English.

**Comment by michoael** [comment]
I thought can translate to any languages.
Now when i return translate false and language equal ar, it can listen it good. Thank you.
